### ISSUE TITLE
Remove unneeded functions for statistics, ect

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#4]
Statistics calculations should be done on a front-end not inside stratum.

Daemons should be made to be light, efficient and stable.

**Comment by moopless** [comment]
Stripped out many of the features in the stratum-lite branch. Check out 44b50c468e30d8606c86686812c99b13720df611 and let me know what you think.

**Comment by moopless** [comment]
Closing with the stratum-lite branch.

**Comment by Neozonz** [comment]
Add do not check password feature to stratum-lite branch.

Very useful feature

**Comment by moopless** [comment]
Implemented in 1072f01917e88e820bd9c8bb4d7015e6a572ada4

**Comment by Neozonz** [comment]
If Username is not correct causes exception

BACKTRACK

 [2013-06-13 00:45:08] Started cgminer 3.2.0

 [2013-06-13 00:45:08] Started cgminer 3.2.0
 [2013-06-13 00:45:08] Loaded configuration file cgminer.conf
 [2013-06-13 00:45:09] Probing for an alive pool
 [2013-06-13 00:45:09] Pool 0 difficulty changed to 16.000000
 [2013-06-13 00:45:09] pool 0 JSON stratum auth failed: [
   -1,
   "'NoneType' object has no attribute '**getitem**'",
   "Traceback: <type 'exceptions.TypeError'>: 'NoneType' object has no attribute
 '**getitem**'\n/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/
stratum/protocol.py:185:dataReceived\n/usr/local/lib/python2.7/dist-packages/str
atum-0.2.12-py2.7.egg/stratum/protocol.py:230:lineReceived\n/usr/local/lib/pytho
n2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:13:_han

**Comment by moopless** [comment]
Fixed in 94385e58903a6cd360d3da1929df3b59d3ee24bc

**Comment by Neozonz** [comment]
Regardng removing unneeded functions, ect:
Still see the daemon trying to update stats.print or something along those lines...
Also is it possible to maybe code in stratum lite mode into a configurational change. It would help maintaining code, instead of two branches have a flag for lite stratum mode in config.py

**Comment by moopless** [comment]
Sounds good. Let me know what it's complaining about and I will remove it
from this branch.

**Comment by moopless** [comment]
Is this the message that you see?
2013-06-13 23:20:48,940 INFO stats # 1 peers connected, state changed 1 times

That is buried in stratum protocol.py and is printed when a peer connects or disconnects. It can safely be ignored as it will have a very minimal impact.

**Comment by Neozonz** [comment]
Yup that's the message. Sorry I should have taken a better look, I had thought it was running some of the stratum statistic functions for hashrate/difficulty/shares, ect

Closing Issue

**Comment by Neozonz** [comment]
Latest commit is having password check functionality issues,
Cannot login with false passwords anymore :(

2013-06-29 11:49:20,442 ERROR protocol protocol.process_failure # [Failure instance: Traceback: <type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:185:dataReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:230:lineReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:13:_handle_event
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:81:call
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:134:maybeDeferred
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:78:_run
/home/stratum-mining-litecoin/mining/service.py:81:submit
/home/stratum-mining-litecoin/mining/interfaces.py:24:authorize
/home/stratum-mining-litecoin/mining/DBInterface.py:135:check_password
]
None

**Comment by moopless** [comment]
Should be fixed. That back trace is because I was not type casting and someone sent in garbage input. It should not backtrace now. Please open new issues for this for better tracking in the git log.
